import type { Metadata } from "next";
import styles from "./layout.module.css";
import clsx from "clsx";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Trueba técnica Alfred",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={clsx(geistSans.variable, geistMono.variable, styles.container, "antialiased")}
      >
        <div className={styles.background}></div>
        <div className={clsx("mx-auto px-4 w-full sm:max-w-[550px] md:max-w-[680px] lg:max-w-[980px]  xl:max-w-7xl", styles.mainContent)}>
          <Providers>
            {children}
          </Providers>
          <footer className="py-8 px-8 text-center">
            <p>Made with ❤️ by <a href="https://github.com/gabrielceh" target="_blank" rel="noreferrer">Gabriel Cervantes Hurtado</a></p>
          </footer>
        </div>
      </body>
    </html>
  );
}
